### PR TITLE
fix: Runners are terminated due to incorrect time logic. fixes #1889

### LINKED ISSUE #1889: Runners are terminated due to incorrect time logic based on idle config cron expression.
We have defined Idle config to maintain runner count on weekday and weekend. We have below Idle config,

```
idle_config = [{
  cron      = "* * * * * 1-5" // Runs monday to friday cron parser format - https://www.npmjs.com/package/cron-parser     timezone reference - https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  timeZone  = "GMT"
  idleCount = 2
  },
  {
    cron      = "* * * * * 6-7" // runs Saturday and Sunday as per GMT timezone
    timeZone  = "GMT"
    idleCount = 1
}]
```

The function  "https://github.com/philips-labs/terraform-aws-github-runner/blob/develop/modules/runners/lambdas/runners/src/scale-runners/scale-down-config.ts#L22"
is returing the value '0' and causing the runners to terminate. This is leading to continuous launch and termination of runners if Pooling feature is enabled.

We dont have a solution to this issue right now. Sharing the issue which we faced over the weekend.

We tried to debug the code and below is the information.

```
`var parser = require("cron-parser");
var moment = require("moment");

var scalingDownConfigs = [
  { cron: "* * * * * 1-5", idleCount: 2, timeZone: "GMT" },
  { cron: "* * * * * 6-7", idleCount: 1, timeZone: "GMT" },
];

function inPeriod(period) {
  const now = moment(new Date());
  console.log("now-->", now);
  const expr = parser.parseExpression(period.cron, {
    tz: period.timeZone,
  });
  //console.log("expr-->", expr);
  const next = moment(expr.next().toDate());
  console.log("next-->", next);
  console.log("next.diff-->", next.diff(now, "seconds"));
  console.log(Math.abs(next.diff(now, "seconds")));
  return Math.abs(next.diff(now, "seconds")) < 5; // we keep a range of 5 seconds
}

for (const scalingDownConfig of scalingDownConfigs) {
  console.log("Input Config-->", scalingDownConfig);
  if (inPeriod(scalingDownConfig)) {
    console.log("scalingDownConfig.idleCount--->", scalingDownConfig.idleCount);
  }
}
console.log("Outside For loop-->output-->", 0);`
```

```
Output:

`Input Config--> { cron: '* * * * * 1-5', idleCount: 2, timeZone: 'GMT' }
now--> Moment<2022-03-26T20:59:40-04:00>
next--> Moment<2022-03-27T20:00:00-04:00>
next.diff--> 82819
82819

Input Config--> { cron: '* * * * * 6-7', idleCount: 1, timeZone: 'GMT' }
now--> Moment<2022-03-26T20:59:40-04:00>
next--> Moment<2022-04-01T20:00:00-04:00>
next.diff--> 514819
514819
Outside For loop-->output--> 0`

```

### PR DESCRIPTION
**Pull request by shashidhar087**
fixes issue #1889

### CODE REVIEW

**Comment by npalm** [comment]
@PatrickMennen do you have time to have a look on this PR?

**Comment by npalm** [comment]
@shashidhar087 I have tried to reproduce the issue, but with the current main branch non of my idle runners got terminated after midnight. Please can you share the idle config and scale down config to reproduce the issue?

**Comment by shashidhar087** [comment]
> @shashidhar087 I have tried to reproduce the issue, but with the current main branch non of my idle runners got terminated after midnight. Please can you share the idle config and scale down config to reproduce the issue?

@npalm  

idle_config = [{
  cron      = "* * * * * 1-5" // Runs monday to friday cron parser format - https://www.npmjs.com/package/cron-parser     timezone reference - https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  timeZone  = "GMT"
  idleCount = 2
  },
  {
    cron      = "* * * * * 6-7" // runs Saturday and Sunday as per GMT timezone
    timeZone  = "GMT"
    idleCount = 1
}]


Issue occurs every friday midnight and sunday midnight

**Comment by npalm** [comment]
> https://www.npmjs.com/package/cron-parser

Thx, will run a few tests over the next days.

**Comment by npalm** [comment]
Tested, so far looks good.

**Comment by npalm** [comment]
Sorry for keep you wating, ran some tests. And the test are working. But we have clearly a gap in the unit tests. Tried to write a unit test to prove the issue, but so far got not a unit testing working.

**Comment by npalm** [comment]
I have tried to create a unit test for the problem. According the PR the problems is the date transiton. I have added the following test

jest config
```JavaScript
process.env.TZ = 'UTC';

module.exports ....
```

And next a test like this. 

```TypeScript
    it('Test day transtion for 2 rules', async () => {
      process.env.TZ = 'UTC';
      const d = new Date(2022, 4, 20, 23, 59, 55, 0);
      jest.useFakeTimers('modern')
      jest.setSystemTime(d)

      const scaleDownConfig: ScalingDownConfigList = [{
        cron: '* * * * * 1-5',
        idleCount: 2,
        timeZone: 'GMT'
      }, {
        cron: '* * * * * 6',
        idleCount: 1,
        timeZone: 'GMT'
      }]

      const count = getIdleRunnerCount(scaleDownConfig);
      expect(count).toEqual(2);

      jest.useRealTimers()
    })
```
Only when I change the time to 23:59, the test fails. Since 1 is returned instead of 2.

So still puzzled to understand what is going wrong.

**Pull request closed without merging**
