### PR TITLE
fix: Adding github URL to config.cmd

### PR DESCRIPTION
**Pull request by rfsmart-bcleary**
#3737 This adds the variable gh_url, creates a SSM parameter containing the value from gh_url, and passes in the value of gh_url to the config.cmd call.

### CODE REVIEW

**Comment by dhlaurap** [comment]
Hello, I am running into this issue, when could this be available in a release?

**Comment by dhlaurap** [comment]
I was just looking at this more closely and since multiple repos can use the runner would it be better if the webhook lambda stored the repo URL (from the webhook payload) into SSM for the runner to pick-up when running the user_data script?

**Comment by jonanderson10** [comment]
+1 I am seeing this issue as well

**Comment by dhlaurap** [comment]
I actually ended up fixing this by using a custom image and modifying the start-runner script by removing the `.\config.cmd` call and adding the `--jitconfig` argument to the run.cmd action like this:

`$action = New-ScheduledTaskAction -WorkingDirectory "$pwd" -Execute "run.cmd" -Argument "--jitconfig $config"`

From what I could gather, a similar fix went into the linux start-runner script but the Windows one was never fixed.

**Comment by ardole** [comment]
@dhlaurap can you confirm which version of the github runner are you using please ?

- i face the same issue with `--token`, to me its https://github.com/actions/runner/issues/1882 

- your solution with `jitconfig` seems to not work with [v2.317.0](https://github.com/actions/runner/releases/tag/v2.317.0) argument is not recognized and nothing better with argument `ephemeral`. i'm wondering why the `start-runner.ps1` and `start-runner.sh` are different because for windows platforms `enable_ephemeral_runners` and `enable_jit_config` are simply ignored, runner is always starting as a service.

this project is great but seems to suffer of a lack of testability (or i haven't found it), can somebody give tricks on how to quickly test the AMI without need to deploy the whole lambdas ? for instance `start-runner.ps1` depends on a **ssm-parameters** and registration done in lambdas.

**Comment by ardole** [comment]
You are right, something was wrong with the `$config` that i generated manually to debug.
After new try i was able to make it working with the argument you suggested.

I opened a new issue https://github.com/philips-labs/terraform-aws-github-runner/issues/3950 and suggest a simple fix https://github.com/philips-labs/terraform-aws-github-runner/pull/3951

**Pull request closed without merging**
