### PR TITLE
WIP: Added windows action runner support

### PR DESCRIPTION
**Pull request by BrianGuo987**
User can choose to use which AMIs/ multiple AMIs to launch the ec2 instance, but still not finish all the things e.g. support both Linux and Windows AMIs at the same time.
at least the Windows user data should help.

Thanks,
Brian

### CODE REVIEW

**Comment by npalm** [comment]
@BrianGuo987 thanks a lot, let us know if you are planning to resolve the remaning issues you mention. Meanwhile I whill have a look on the work you did next week.

**Comment by BrianGuo987** [comment]
@npalm  I'm busy with something recently so I don't have time to fix all the things at least for a few  months.
Thanks

**Comment by npalm** [comment]
> > Nice to see you are busy with adding a windows runner, just wondering what the current status is. Would be great if you can open a PR, even while you are in a WIP status. Just mark your PR as in progress.
> 
> Hi Niek,
> I'm not so confident to finish all the things because I haven't done the investigation yet, if I make any progress I will open a PR.
> Thanks

Thanks will have a look. I will update the title to WIP of the PR so it is clear to everyone it is not finished yet. 

For my understanding. So both windows as linux are working as long you don't mix them?

**Comment by BrianGuo987** [comment]
Yes, but I don’t know how to get the labels in the yaml file that user specified.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by ScottGuymer** [comment]
I'm working on merging the existing branch into develop now in #1476.

Any help in reviewing that or suggestion you have would be appreciated.

Happy with closing this in favour of #1476?

**Comment by npalm** [comment]
Yes agree to close this PR.

**Comment by ScottGuymer** [comment]
Closing this in favour of #1476

**Pull request closed without merging**
