### PR TITLE
fix(ghes): Adds header for preview API

### PR DESCRIPTION
**Pull request by mcaulifn**

### CODE REVIEW

**Comment by mcaulifn** [comment]
@npalm This should resolve #478 and supersede #479

**Comment by mcaulifn** [comment]
I confirmed this works against 2.22.3.

**Comment by npalm** [comment]
Just checked AWS deployment, all works fine

**Review by npalm — APPROVED** [review]

**Comment by npalm** [comment]
@gr2m thanks for the hint

**Comment by npalm** [comment]
close #478

**Pull request merged**
