### PR TITLE
docs: Typo's and clarifications

### PR DESCRIPTION
**Pull request by sdarwin**
Hi,

I believe these proposed changes are right, but your feedback is welcome!

Ideas for further improvements to the README file:  
When configuring the github app, add small screenshots from github.com, and in the text be clear about the Page, Section, and Entry. For example, it says "Enable the webhook". Where is that? Is the setting named "Enable the webhook"? Of course, the user can eventually find it. But if they are on the "Permissions & Events" page, it's not visible.

### CODE REVIEW

**Review by npalm — APPROVED** [review]

**Comment by npalm** [comment]
@sdarwin thanks, can you re-base the PR?

**Comment by sdarwin** [comment]
That's a surprise, commit 353c060e6758c4aeba23b9456f1470c257bd4df1 automatically reverted my previous README.md updates.

Probably the same thing will happen to this pull request. It will be overwritten by dependabot.  

In that case this PR shouldn't be merged yet.  I must figure out which other files to modify.

**Comment by sdarwin** [comment]
OK in the latest changes I have modified `variables.tf` in addition to the README file.   Presumably that's the source data.   Otherwise let me know.

**Comment by sdarwin** [comment]
HI @npalm I re-based this PR, it should be fine to merge.

**Review by npalm — APPROVED** [review]
@sdarwin thanks!

**Pull request merged**
