### PR TITLE
WIP Add option to set github server url #303

### PR DESCRIPTION
**Pull request by npalm**

### CODE REVIEW

**Comment by npalm** [comment]
Verified with default example

**Comment by mm-matsuda** [comment]
Thanks PR!

But the request still go to github.com.

```
2020-11-05T05:30:38.402Z	9b7e2f8d-a202-5a23-b1f6-7790322ad542	ERROR	RequestError [HttpError]: Integration not found
    at /var/task/index.js:14468:23
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async getInstallationAuthentication (/var/task/index.js:1546:7) {
  status: 404,
  headers: {
    'access-control-allow-origin': '*',
    'access-control-expose-headers': 'ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, Deprecation, Sunset',
    connection: 'close',
    'content-encoding': 'gzip',
    'content-security-policy': "default-src 'none'",
    'content-type': 'application/json; charset=utf-8',
    date: 'Thu, 05 Nov 2020 05:30:38 GMT',
    'referrer-policy': 'origin-when-cross-origin, strict-origin-when-cross-origin',
    server: 'GitHub.com',
    status: '404 Not Found',
    'strict-transport-security': 'max-age=31536000; includeSubdomains; preload',
    'transfer-encoding': 'chunked',
    vary: 'Accept-Encoding, Accept, X-Requested-With',
    'x-content-type-options': 'nosniff',
    'x-frame-options': 'deny',
    'x-github-media-type': 'github.v3; param=machine-man-preview; format=json',
    'x-github-request-id': '8650:63C0:B7CA05:ED3726:5FA38DFE',
    'x-xss-protection': '1; mode=block'
  },
  request: {
    method: 'POST',
    url: 'https://api.github.com/app/installations/14/access_tokens',
    headers: {
      accept: 'application/vnd.github.machine-man-preview+json',
      'user-agent': 'octokit-auth-app.js/2.4.11 Node.js/12.18.4 (linux; x64)',
      authorization: 'bearer [REDACTED]',
      'content-type': 'application/json; charset=utf-8'
    },
    body: '{}'
  },
  documentation_url: 'https://docs.github.com/rest'
}
```

Where are you requesting access_token?
In Github Enterprise Server, url is `https://${github_server_url}/api/v3/app/installations/14/access_tokens`

**Comment by npalm** [comment]
We also need to set somewhere the backend for the API calls since the lambda are makin all kind of API calls

**Comment by WilliamDuTrendMicro** [comment]
Thanks PR!

we also would like to test on the Github EE.

**Comment by npalm** [comment]
Looks like a bit more work, since all API call by the lambda's need to be sent to the EE server

**Comment by mcaulifn** [comment]
@npalm do you want commits against this branch or would you prefer I create a new one and raise a PR against your branch or `master`?

**Comment by npalm** [comment]
> @npalm do you want commits against this branch or would you prefer I create a new one and raise a PR against your branch or `master`?

@mcaulifn feel free to creater a fresh branch based on `develop`. No reason to branch from this branch.

**Pull request closed without merging**
