### PR TITLE
feat(runners): Add possibility to not create ebs

### PR DESCRIPTION
**Pull request by Hunqer**
For issue: https://github.com/philips-labs/terraform-aws-github-runner/issues/1769

### CODE REVIEW

**Comment by Hunqer** [comment]
Not sure if its a proper solution, really hard to test it as module is complicated.

**Comment by npalm** [comment]
Can you share some config how you setup the ebs? Are you using an AMI (ubuntu) I guess?

**Comment by Hunqer** [comment]
> Can you share some config how you setup the ebs? Are you using an AMI (ubuntu) I guess?

We are using ubuntu AMI and dont setup ebs (module takes default) in that case which is `{}` and ebs with default values is created.

**Comment by npalm** [comment]
Thx, will check asap

**Comment by Hunqer** [comment]
> Thx, will check asap

@npalm have you managed to check it?

**Review by npalm — APPROVED** [review]
@Hunqer thanks LGTM

**Pull request merged**
