### PR TITLE
feat: Log job runtime for `completed` events (#3687)

### LINKED ISSUE #3687: Feature Request: Adding job runtimes to webhook logs
### Discussed in https://github.com/philips-labs/terraform-aws-github-runner/discussions/3686

<div type='discussions-op-text'>

<sup>Originally posted by **winwinashwin** December 23, 2023</sup>

Motivation
---
I would like to monitor our CI runtimes at job-level across our organization. A simple way to go about this would be to craft a cloudwatch query to filter the job logs from the webhook lambda and graph the runtimes. The `completed` event logs have the `started_at` and `completed_at` datetime fields but cloudwatch query syntax does not support parsing human readable timestamps as of today (according to official docs). 

Computing the runtime within the lambda and adding this field to the logs will allow monitoring CI runtimes in cloudwatch natively without any hassle.

---

If approved I would love to open a PR for this feature. I believe this should be straightforward addition right about [here](https://github.com/philips-labs/terraform-aws-github-runner/blob/9a2ed66aa5004b5ad41106908af48665e49d32f6/lambdas/functions/webhook/src/webhook/index.ts#L137)
</div>

### PR DESCRIPTION
**Pull request by winwinashwin**
Closes #3687

### CODE REVIEW

**Comment by winwinashwin** [comment]
@npalm Could you please review?

**Comment by winwinashwin** [comment]
@npalm Any comments on this?

**Comment by npalm** [comment]
Thanks for the PR, I have some huge backlog. Doing my best to dig in the PR asap.

**Comment by npalm** [comment]
I will check the PR asap. sorry for the delay

**Comment by winwinashwin** [comment]
@GuptaNavdeep1983 From the [comment](https://github.com/philips-labs/terraform-aws-github-runner/issues/3687#issuecomment-1888699629) under the linked issue I thought adding the runtime computation logic in the lambda was discouraged in favour of the experimental event bridge, which is why I refrained from working further on this PR.

If you are okay with merging this change please make it clear so that I can work on this, else I understand your decision and we can close this PR.

**Pull request closed without merging**
