### PR TITLE
chore: Refactor runnerServiceConfig to be an array of strings

### PR DESCRIPTION
**Pull request by ulich**
Fixes https://github.com/philips-labs/terraform-aws-github-runner/issues/1522

### CODE REVIEW

**Comment by ulich** [comment]
I see Sonar complaining about some duplication of code in the scale-up.test.ts. I actually disagree here with Sonar, trying to reduce the duplication would result in less readable/understandable testing code.

What is your approach usually in this case?

**Comment by npalm** [comment]
@ulich please ignore Sonar for now, it was an experiment to add it. Still have to see how we can value out of sonar, but for now ignore it. Will remove it next week

**Comment by ulich** [comment]
Ok. Then the PR is ready for review

**Review by npalm — APPROVED** [review]
@ulich thanks LGTM

**Pull request merged**
