### PR TITLE
Add delay to prevent ssm rate limits using setTimeout

### PR DESCRIPTION
**Pull request by devsh4**
Adding a fix for bug #1841 which prevents hitting AWS SSM rate limits by adding a delay between subsequent `putParameter` calls.

These lines had no code coverage, however all pre commit checks passed and I was able to successfully build it.

**Note**: 25ms delay is based on the [AWS service quotas](https://docs.aws.amazon.com/general/latest/gr/ssm.html#limits_ssm) as they only allow 40 requests per second to the parameter store by default.

### CODE REVIEW

**Comment by npalm** [comment]
Did a quick check, with 40 runners I get throttle exceptions. Please can you have a look at the CI builds as well.

**Comment by devsh4** [comment]
Yes CI should be fixed now.

**Comment by npalm** [comment]
In you next PR's an approval would not be required anymore :)

**Comment by devsh4** [comment]
Regarding the test failure, it occurred when I ran locally even without my changes.

**Comment by npalm** [comment]
Did you use node14?

**Comment by devsh4** [comment]
> Did you use node14?

Yes it's possible I used the latest version.

**Comment by devsh4** [comment]
@npalm I fixed the failing test. Please approve the build when you can.

image

**Review by ScottGuymer — COMMENTED** [review]
I'm not sure I'm happy with the approach of adding a fixed delay in here. It effectively increases the execution time of every execution of the lambda by 25ms regardless of if it would be throttled or not. Which translates to a direct cost for each lambda execution.

Are there some better approaches we can come up with such as building in retries for failure and/or some kind of circuit breaker (or anything else)?

**Comment by devsh4** [comment]
> I'm not sure I'm happy with the approach of adding a fixed delay in here. It effectively increases the execution time of every execution of the lambda by 25ms regardless of if it would be throttled or not. Which translates to a direct cost for each lambda execution.
> 
> Are there some better approaches we can come up with such as building in retries for failure and/or some kind of circuit breaker (or anything else)?

Good point, I'll add a check on the instance count and add a fixed delay only if it's more than 40 instances (according to the rate limit).

**Comment by devsh4** [comment]
Ah rebase went wrong, closing this PR in lieu of new one.

**Pull request closed without merging**
