### PR TITLE
feat: Add Support for Amazon Linux 2023

### PR DESCRIPTION
**Pull request by eabrouwer3**
First attempt at resolving issue #2848. However, because the latest supported Amazon Linux version is now 2023, this PR has been updated to use `al2023` by default.

### CODE REVIEW

**Comment by npalm** [comment]
I think it would be better that we replace Amazon Linux 2 by default to 2022

**Comment by eabrouwer3** [comment]
@npalm I agree, if we're ok with that. I'll update my PR to do that.

**Comment by eabrouwer3** [comment]
@npalm I've checked my PR according to the `CONTRIBUTING.md` guidelines, squashed all my commits into one, and also updated the PR to bump up to al2023 instead of al2022 because that's the most current supported version. I couldn't find all the necessary details for the packer files for the al2022 versions. Let me know what you think and if I need to change/update anything else!

**Comment by GuptaNavdeep1983** [comment]
@eabrouwer3 All the files relevant for packer are under images folder and the install/start scripts are under modules folder.

**Comment by eabrouwer3** [comment]
@GuptaNavdeep1983, what I mean is that I couldn't find the `al2022` AMI when searching in the EC2 console. And I needed to find that to double check the image name format, and get the `owner` for the packer file. I figured everything out for the `al2023` image though.

**Comment by eabrouwer3** [comment]
Closing this PR in favor of making it on a new branch (made the PR off of my `main`, making it hard to sync with the forked repo's `main`).

**Pull request closed without merging**
