### PR TITLE
fix(runners) - Revert octokit rest #386 and fixate dependency. (#478)

### PR DESCRIPTION
**Pull request by npalm**
See #478

### CODE REVIEW

**Comment by npalm** [comment]
@jonico @mcaulifn please can you verify the PR for GHES?

**Comment by jonico** [comment]
@mcaulifn: This was exactly the fix I applied locally which made it work again

**Comment by mcaulifn** [comment]
Our test instance is down due to a failed upgrade to 3.0 RC. I cannot test it right now. I would suggest merging for now while investigation continues.

**Comment by jonico** [comment]
This might be slightly off-topic but I noticed today that the EC-2 runners did no longer properly connect to GitHub Enterprise Server with the latest runner binaries.
From the runners log:

```
  | 2021-01-20T14:55:54.932+01:00 | x-tfs-processid: 98044e3b-313d-42e8-8674-fc387d67f23d
  | 2021-01-20T14:55:54.932+01:00 | activityid: 2a07b621-ed6d-4857-be58-7df581d07be4
  | 2021-01-20T14:55:54.932+01:00 | x-tfs-session: cfdc1d98-dc29-4348-9652-d9d29ed3a1ed
  | 2021-01-20T14:55:54.932+01:00 | x-vss-e2eid: a119b94a-10a8-4819-9956-5b804088aefd
  | 2021-01-20T14:55:54.932+01:00 | x-vss-senderdeploymentid: 4fa63284-cff6-c043-679c-da198ae687a5
  | 2021-01-20T14:55:54.932+01:00 | x-tfs-serviceerror: The+user+%27System%3aPublicAccess%3baaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa%27+is+not+authorized+to+access+this+resource.
  | 2021-01-20T14:55:54.932+01:00 | x-vss-s2stargetservice: 0000005A-0000-8888-8000-000000000000/visualstudio.com
  | 2021-01-20T14:55:54.932+01:00 | X-Frame-Options: DENY
  | 2021-01-20T14:55:54.932+01:00 | [2021-01-20 13:55:54Z INFO RSAFileKeyManager] Loading RSA key parameters from file /home/ec2-user/actions-runner/.credentials_rsaparams
  | 2021-01-20T14:55:55.182+01:00 | [2021-01-20 13:55:54Z INFO RSAFileKeyManager] Loading RSA key parameters from file /home/ec2-user/actions-runner/.credentials_rsaparams
  | 2021-01-20T14:55:55.182+01:00 | [2021-01-20 13:55:55Z ERR GitHubActionsService] POST request to https://octodemo.com/_services/vstoken/_apis/oauth2/token/0f19532c-dde1-414e-b81b-4127816fc91c failed. HTTP Status: BadRequest
  | 2021-01-20T14:55:55.182+01:00 | [2021-01-20 13:55:55Z INFO GitHubActionsService] AAD Correlation ID for this token request: Unknown
  | 2021-01-20T14:55:55.182+01:00 | [2021-01-20 13:55:55Z ERR Runner] GitHub.Services.OAuth.VssOAuthTokenRequestException: The signature is not valid. at GitHub.Services.OAuth.VssOAuthTokenProvider.OnGetTokenAsync(IssuedToken failedToken, CancellationToken cancellationToken) at GitHub.Services.Common.IssuedTokenProvider.GetTokenOperation.GetTokenAsync(VssTraceActivity traceActivity) at GitHub.Services.Common.IssuedTokenProvider.GetTokenAsync(IssuedToken failedToken, CancellationToken cancellationToken) at GitHub.Services.Common.VssHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) at GitHub.Services.Common.VssHttpRetryMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, CancellationToken cancellationToken) at GitHub.Services.WebApi.VssHttpClientBase.SendAsync(HttpRequestMessage message, HttpCompletionOption completionOption, Object userState, CancellationToken cancellationToken) at GitHub.Services.WebApi.VssHttpClientBase.SendAsync[T](HttpRequestMessage message, Object userState, CancellationToken cancellationToken) at GitHub.Services.WebApi.VssHttpClientBase.SendAsync[T](HttpMethod method, IEnumerable`1 additionalHeaders, Guid locationId, Object routeValues, ApiResourceVersion version, HttpContent content, IEnumerable`1 queryParameters, Object userState, CancellationToken cancellationToken) at GitHub.Runner.Listener.Configuration.ConfigurationManager.ConfigureAsync(CommandSettings command) at GitHub.Runner.Listener.Runner.ExecuteCommand(CommandSettings command)
  | 2021-01-20T14:55:55.182+01:00 | [2021-01-20 13:55:55Z ERR Terminal] WRITE ERROR: The signature is not valid.
```

I reproduced the problem locally on my Mac with the newest runner release: https://github.com/actions/runner/releases/tag/v2.276.0
... same error "The signature is not valid." when trying to configure the runner with GitHub Enterprise Server 2.22

When I overrode the content of the S3 bucket with the previous version (https://github.com/actions/runner/releases/tag/v2.275.1) things started working again.

So far, I just disabled the lambda cron trigger - but I wonder whether it would make sense to have an option to fixate the number of the runner binaries as well?

**Comment by jonico** [comment]
Update: I reported the issue to my GitHub colleagues and there will be a fix for the latest runner version out there soon.

**Comment by mcaulifn** [comment]
I was able to get the test instance back up and tested this branch. It worked as expected. :shipit:

**Comment by npalm** [comment]
> This might be slightly off-topic but I noticed today that the EC-2 runners did no longer properly connect to GitHub Enterprise Server with the latest runner binaries.
> From the runners log:
> 
> ```
>   | 2021-01-20T14:55:54.932+01:00 | x-tfs-processid: 98044e3b-313d-42e8-8674-fc387d67f23d
>   | 2021-01-20T14:55:54.932+01:00 | activityid: 2a07b621-ed6d-4857-be58-7df581d07be4
>   | 2021-01-20T14:55:54.932+01:00 | x-tfs-session: cfdc1d98-dc29-4348-9652-d9d29ed3a1ed
>   | 2021-01-20T14:55:54.932+01:00 | x-vss-e2eid: a119b94a-10a8-4819-9956-5b804088aefd
>   | 2021-01-20T14:55:54.932+01:00 | x-vss-senderdeploymentid: 4fa63284-cff6-c043-679c-da198ae687a5
>   | 2021-01-20T14:55:54.932+01:00 | x-tfs-serviceerror: The+user+%27System%3aPublicAccess%3baaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa%27+is+not+authorized+to+access+this+resource.
>   | 2021-01-20T14:55:54.932+01:00 | x-vss-s2stargetservice: 0000005A-0000-8888-8000-000000000000/visualstudio.com
>   | 2021-01-20T14:55:54.932+01:00 | X-Frame-Options: DENY
>   | 2021-01-20T14:55:54.932+01:00 | [2021-01-20 13:55:54Z INFO RSAFileKeyManager] Loading RSA key parameters from file /home/ec2-user/actions-runner/.credentials_rsaparams
>   | 2021-01-20T14:55:55.182+01:00 | [2021-01-20 13:55:54Z INFO RSAFileKeyManager] Loading RSA key parameters from file /home/ec2-user/actions-runner/.credentials_rsaparams
>   | 2021-01-20T14:55:55.182+01:00 | [2021-01-20 13:55:55Z ERR GitHubActionsService] POST request to https://octodemo.com/_services/vstoken/_apis/oauth2/token/0f19532c-dde1-414e-b81b-4127816fc91c failed. HTTP Status: BadRequest
>   | 2021-01-20T14:55:55.182+01:00 | [2021-01-20 13:55:55Z INFO GitHubActionsService] AAD Correlation ID for this token request: Unknown
>   | 2021-01-20T14:55:55.182+01:00 | [2021-01-20 13:55:55Z ERR Runner] GitHub.Services.OAuth.VssOAuthTokenRequestException: The signature is not valid. at GitHub.Services.OAuth.VssOAuthTokenProvider.OnGetTokenAsync(IssuedToken failedToken, CancellationToken cancellationToken) at GitHub.Services.Common.IssuedTokenProvider.GetTokenOperation.GetTokenAsync(VssTraceActivity traceActivity) at GitHub.Services.Common.IssuedTokenProvider.GetTokenAsync(IssuedToken failedToken, CancellationToken cancellationToken) at GitHub.Services.Common.VssHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) at GitHub.Services.Common.VssHttpRetryMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, CancellationToken cancellationToken) at GitHub.Services.WebApi.VssHttpClientBase.SendAsync(HttpRequestMessage message, HttpCompletionOption completionOption, Object userState, CancellationToken cancellationToken) at GitHub.Services.WebApi.VssHttpClientBase.SendAsync[T](HttpRequestMessage message, Object userState, CancellationToken cancellationToken) at GitHub.Services.WebApi.VssHttpClientBase.SendAsync[T](HttpMethod method, IEnumerable`1 additionalHeaders, Guid locationId, Object routeValues, ApiResourceVersion version, HttpContent content, IEnumerable`1 queryParameters, Object userState, CancellationToken cancellationToken) at GitHub.Runner.Listener.Configuration.ConfigurationManager.ConfigureAsync(CommandSettings command) at GitHub.Runner.Listener.Runner.ExecuteCommand(CommandSettings command)
>   | 2021-01-20T14:55:55.182+01:00 | [2021-01-20 13:55:55Z ERR Terminal] WRITE ERROR: The signature is not valid.
> ```
> 
> I reproduced the problem locally on my Mac with the newest runner release: https://github.com/actions/runner/releases/tag/v2.276.0
> ... same error "The signature is not valid." when trying to configure the runner with GitHub Enterprise Server 2.22
> 
> When I overrode the content of the S3 bucket with the previous version (https://github.com/actions/runner/releases/tag/v2.275.1) things started working again.
> 
> So far, I just disabled the lambda cron trigger - but I wonder whether it would make sense to have an option to fixate the number of the runner binaries as well?

In my opinion it shulld possbile to let the user decide on when to update the runner binary. But the github action runner is updating it self (see also https://github.com/actions/runner/issues/246). I think it would be better to let the user choose when o update and have a strategy on how many version you can be behind. 

Just wondering you used an older version of the runner which you put in S3. Once installed is the runner not updating it self?

**Comment by npalm** [comment]
> Update: I reported the issue to my GitHub colleagues and there will be a fix for the latest runner version out there soon.

@jonico can you also discuss with your colleagues how we can proceed with the octokit/rest.js lib. I like to beable to move on with new versions once possible.

**Comment by mcaulifn** [comment]
https://github.com/octokit/rest.js/issues/1983 leaves a vague suggestion of using `mediaType` but its not obvious where to use this.

**Comment by npalm** [comment]
So it looks like we can simply add a the mediatype suggested to the created client: https://github.com/philips-labs/terraform-aws-github-runner/blob/790971ced6f04506300893caf41f3067ef96ca6e/modules/runners/lambdas/runners/src/scale-runners/gh-auth.ts#L51

```TypeScript
  if (ghesApiUrl) {
    authOptions.request = request.defaults({
      baseUrl: ghesApiUrl,
      mediaType: { previews: ['antiope'] } 
    });
  }
```

**Comment by npalm** [comment]
PR should be obsolete once PR #481 is merged

**Comment by npalm** [comment]
obsolete

**Pull request closed without merging**
