### PR TITLE
fix: block name should default to `dev/xvda`

### PR DESCRIPTION
**Pull request by gusfune**
This fixes the issue reported on #2017.

### CODE REVIEW

**Comment by npalm** [comment]
close #2017

**Review by npalm — APPROVED** [review]

**Review by ScottGuymer — APPROVED** [review]
LGTM

Nice catch

**Comment by npalm** [comment]
Defaults in variables files are available in 2 files. One in the root and one per module, this to let users use the module per module or as whole. To provide a quick release I have opend a PR on top of this #2019  with the fixed. @gusfune thanks for you fast response and quick fix. We value your contribution!

**Comment by npalm** [comment]
closing in fovour of #2019

**Pull request closed without merging**
