### PR TITLE
fix(examples): Upgrading ubuntu example to 22.04

### PR DESCRIPTION
**Pull request by tobiasehlert**
A fresh installation on Ubuntu 22.04 is missing iptables, which is required for rootless docker do work.

- adding iptables apt-get install list
- sorting apt-get install list

### CODE REVIEW

**Review by npalm — COMMENTED** [review]
@tobiasehlert thx for your PR. The example is still on ubuntu20.04 which seems not require the iptables. So suggest we combine the PR with an upgade of the example to ubuntu 22.04. Feel free to update the PR. I leave the PR open for now.

**Comment by npalm** [comment]
Checking now to #2103 to upgrade example to ubuntu 22.04

**Comment by npalm** [comment]
Just tried the example, for some reason the runner cannot find the docker command. On ubuntu-20.04 it all works fine. Tried the PR with and without in combination with #2250

**Comment by tobiasehlert** [comment]
hi @npalm,

I ended up removing docker rootless part and using the "normal" docker as installed from apt after adding the docker repo. I also added some additional steps to add permission to user accounts to use the docker command.
For me that was kind of the best way to get going.

What about adding docker.io as a package to the installing point and not using rootless?
Any reason for us not do to it like that?

**Comment by tobiasehlert** [comment]
@npalm, ah interesting point actually. I've not thought about the volume thing, but we wipe the instances pretty quick, so it's not often they remain even when not using ephemeral runners.

I do actually use an Ansible playbook to setup a instance in the first place and install a couple of software on it (eg. terraform, pip and Docker), since the team want a runner up and running in under 2 minutes. With too much tools getting installed during user-data.sh, the installation takes too long time to finish.
So I have therefore stripped my user-data.sh file quite a lot.

But I can lab today with using rootless and get back to you with my result :)

**Comment by tobiasehlert** [comment]
Ah yeah.. I recall now that docker rootless didn't work for me, since the `/home/$user_name/.profile` file is not read for some reason. I was not able to pinpoint exactly why, so I went for the normal installation instead.

But when I try now to run the export commands to point to `/home/$user_name/.bashrc` instead, it works.

**Comment by tobiasehlert** [comment]
@npalm, so.. not the PR should work better.
I included the changes that are suggested in PR #2103 in the last commit as well, so this update should be complete :)

**Review by npalm — APPROVED** [review]
Thx, tested and looks good!

**Pull request merged**
