### PR TITLE
Standardize Linter Config

### LINKED ISSUE #18: Add lambda linter for runners
Add linting and update workflow, check webhook for examples

### PR DESCRIPTION
**Pull request by mcaulifn**
Standardizes linter config across all lambdas.
Resolves #18

### CODE REVIEW

**Comment by mcaulifn** [comment]
@npalm Not sure what is missing with this function. Any suggestions?

```
/__w/terraform-aws-github-runner/terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/scale-down-config.test.ts
  21:20  error    Unexpected empty arrow function                    @typescript-eslint/no-empty-function
```

**Comment by npalm** [comment]
> @npalm Not sure what is missing with this function. Any suggestions?
> 
> ```
> /__w/terraform-aws-github-runner/terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/scale-down-config.test.ts
>   21:20  error    Unexpected empty arrow function                    @typescript-eslint/no-empty-function
> ```

Looks like line 21 is complete useless, try to remove the line with `before`

**Comment by mcaulifn** [comment]
@npalm All three should be the same. I also cleaned up some of the easier stuff. There are a few more that I wasn't sure if we'd agree on them so I left them out 😄  I also left in but commented out the Google style plugin. That seems to be very popular but it would have created a lot of changes for this PR. Saving it for the next time.

**Review by npalm — COMMENTED** [review]
Looks good to me, @gertjanmaas can you quickly check as well?

**Review by npalm — APPROVED** [review]

**Review by gertjanmaas — APPROVED** [review]
LGTM

**Pull request merged**
