### PR TITLE
refactor: reduce verbosity when customizing some EBS settings for multi-runner

### PR DESCRIPTION
**Pull request by jpalomaki**
Copied from here: https://github.com/philips-labs/terraform-aws-github-runner/blob/main/variables.tf#L267-L280

Should be backwards compatible as the defaults remain the same.

### CODE REVIEW

**Comment by jpalomaki** [comment]
@npalm Looks like checks are failing on an unrelated variable not passing linting

**Comment by npalm** [comment]
> @npalm Looks like checks are failing on an unrelated variable not passing linting

fixed in #3616

**Comment by npalm** [comment]
> @npalm Looks like checks are failing on an unrelated variable not passing linting

can you rebase with main, problem should be resolved

**Comment by jpalomaki** [comment]
@npalm Updated

**Review by npalm — APPROVED** [review]

**Pull request merged**
